version: "3"

services:
  gradio:
    restart: always
    build: .
    ports:
      - "9001:7860"
    networks:
      - demo_network
    image: hitec/demo-frontend

networks:
  demo_network:
    external: true